# yaml-language-server: $schema=https://squidfunk.github.io/mkdocs-material/schema.json
site_name: hard_coded Tech Blog
site_url: https://hard-coders.github.io
theme:
  name: material
  language: ko
  palette:
    - scheme: slate
      primary: indigo
      toggle:
        icon: material/weather-night
        name: Switch to light mode
    - scheme: default
      primary: blue
      toggle:
        icon: material/weather-sunny
        name: Switch to dark mode
  features:
    - navigation.indexes

plugins:
  - blog:
      blog_dir: .
  - tags

nav:
#  - Home: index.md
  - Blog:
    - index.md
    - leetcode
      - index.md

markdown_extensions:
  - pymdownx.superfences
  - pymdownx.keys
  - pymdownx.blocks.admonition:
      types:
      - note
      - attention
      - caution
      - danger
      - error
      - tip
      - hint
      - warning
      - info
      - check
  - pymdownx.blocks.details:
  - pymdownx.blocks.tab:
      alternate_style: True
